# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='collector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x63ollector.proto\"9\n\x06\x43ommon\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\r\x12\x0f\n\x07\x65lapsed\x18\x03 \x01(\x01\"[\n\x0eTimerTelemetry\x12\x17\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x07.Common\x12\x1e\n\nevent_type\x18\x02 \x01(\x0e\x32\n.TimerType\x12\x10\n\x08\x64uration\x18\x03 \x01(\x01\":\n\x11\x44\x61taSizeTelemetry\x12\x17\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x07.Common\x12\x0c\n\x04size\x18\x02 \x01(\x04\"\x10\n\x0eTelemetryReply*3\n\tTimerType\x12\x0b\n\x07READ_IO\x10\x00\x12\x0b\n\x07\x43OMPUTE\x10\x01\x12\x0c\n\x08WRITE_IO\x10\x02\x32{\n\rYuzuCollector\x12\x31\n\x0bReportTimer\x12\x0f.TimerTelemetry\x1a\x0f.TelemetryReply\"\x00\x12\x37\n\x0eReportDataSize\x12\x12.DataSizeTelemetry\x1a\x0f.TelemetryReply\"\x00\x62\x06proto3'
)

_TIMERTYPE = _descriptor.EnumDescriptor(
  name='TimerType',
  full_name='TimerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READ_IO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPUTE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRITE_IO', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=249,
  serialized_end=300,
)
_sym_db.RegisterEnumDescriptor(_TIMERTYPE)

TimerType = enum_type_wrapper.EnumTypeWrapper(_TIMERTYPE)
READ_IO = 0
COMPUTE = 1
WRITE_IO = 2



_COMMON = _descriptor.Descriptor(
  name='Common',
  full_name='Common',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_name', full_name='Common.app_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='Common.step', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elapsed', full_name='Common.elapsed', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=76,
)


_TIMERTELEMETRY = _descriptor.Descriptor(
  name='TimerTelemetry',
  full_name='TimerTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='TimerTelemetry.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='TimerTelemetry.event_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='TimerTelemetry.duration', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=169,
)


_DATASIZETELEMETRY = _descriptor.Descriptor(
  name='DataSizeTelemetry',
  full_name='DataSizeTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='DataSizeTelemetry.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='DataSizeTelemetry.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=229,
)


_TELEMETRYREPLY = _descriptor.Descriptor(
  name='TelemetryReply',
  full_name='TelemetryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=247,
)

_TIMERTELEMETRY.fields_by_name['common'].message_type = _COMMON
_TIMERTELEMETRY.fields_by_name['event_type'].enum_type = _TIMERTYPE
_DATASIZETELEMETRY.fields_by_name['common'].message_type = _COMMON
DESCRIPTOR.message_types_by_name['Common'] = _COMMON
DESCRIPTOR.message_types_by_name['TimerTelemetry'] = _TIMERTELEMETRY
DESCRIPTOR.message_types_by_name['DataSizeTelemetry'] = _DATASIZETELEMETRY
DESCRIPTOR.message_types_by_name['TelemetryReply'] = _TELEMETRYREPLY
DESCRIPTOR.enum_types_by_name['TimerType'] = _TIMERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Common = _reflection.GeneratedProtocolMessageType('Common', (_message.Message,), {
  'DESCRIPTOR' : _COMMON,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:Common)
  })
_sym_db.RegisterMessage(Common)

TimerTelemetry = _reflection.GeneratedProtocolMessageType('TimerTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _TIMERTELEMETRY,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:TimerTelemetry)
  })
_sym_db.RegisterMessage(TimerTelemetry)

DataSizeTelemetry = _reflection.GeneratedProtocolMessageType('DataSizeTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _DATASIZETELEMETRY,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:DataSizeTelemetry)
  })
_sym_db.RegisterMessage(DataSizeTelemetry)

TelemetryReply = _reflection.GeneratedProtocolMessageType('TelemetryReply', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRYREPLY,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:TelemetryReply)
  })
_sym_db.RegisterMessage(TelemetryReply)



_YUZUCOLLECTOR = _descriptor.ServiceDescriptor(
  name='YuzuCollector',
  full_name='YuzuCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=302,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReportTimer',
    full_name='YuzuCollector.ReportTimer',
    index=0,
    containing_service=None,
    input_type=_TIMERTELEMETRY,
    output_type=_TELEMETRYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReportDataSize',
    full_name='YuzuCollector.ReportDataSize',
    index=1,
    containing_service=None,
    input_type=_DATASIZETELEMETRY,
    output_type=_TELEMETRYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_YUZUCOLLECTOR)

DESCRIPTOR.services_by_name['YuzuCollector'] = _YUZUCOLLECTOR

# @@protoc_insertion_point(module_scope)
